language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
xcode_project: RileyLink.xcodeproj
xcode_scheme: RileyLink
script:
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink build -destination 'name=iPhone SE' test
